---
title: "Homework 5.1"
output: html_document
date: "2023-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 2:
```{r}
library(ggplot2)
library(arm)
library(rstanarm)


data <- read.csv(file = 'https://raw.githubusercontent.com/DapperDataAnalyst/Causal_Inference/main/lalonde_5_1.csv', header = T)

# Part c)
## For age
ggplot(data, aes(x = age, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "Age",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

## For black
ggplot(data, aes(x = black, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "Black",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

## For educ
ggplot(data, aes(x = educ, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "Educ",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

## For educ_cat4
ggplot(data, aes(x = educ_cat4, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "educ_cat4",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

## For nodegree
ggplot(data, aes(x = nodegree, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "nodegree",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

## For married
ggplot(data, aes(x = married, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "married",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

## For re75
ggplot(data, aes(x = re75, fill = factor(treat))) +
  geom_histogram(position = "identity", alpha = 0.7, bins = 30) +
  labs(title = "Age Distribution by Treatment",
       x = "re75",
       y = "Frequency") +
  scale_fill_manual(values = c("red", "blue"), name = "Treatment") +
  theme_minimal()

# Part d)
age <- data$age
educ <- data$educ
black <- data$black
married <- data$married
nodegree <-data$nodegree
hisp <- data$hisp
re74 <- data$re74
re75 <- data$re75
re78 <- data$re78
hisp <- data$hisp

model <- stan_glm(treat ~ age+educ+black+married+nodegree+re74+re75+hisp, family=binomial(link="logit"), data=data, refresh=0)
coef(model)
ps_scores <- predict(model, type = "response")
matches <- matching(z=data$treat, score=ps_scores, replace=FALSE)
bal <- balance(rawdat = data[c('age', 'educ', 'black', 'married', 'nodegree', 're74', 're75', 'hisp')],
               treat = data$treat,
               matched = matches$cnts,
               estimand = "ATT")
plot(bal, longcovnames=c('age', 'educ', 're74', 're75'), which.cov="cont")
plot(bal, longcovnames=c('black', 'married', 'nodegree', 'hisp'), which.cov="binary")
```

